# Generated by Django 3.2.25 on 2024-07-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealership', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exterior_color', models.CharField(max_length=50)),
                ('interior_color', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
                ('fuel_economy', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=17)),
                ('stock_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('listing_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
