# Generated by Django 3.2.25 on 2024-07-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclelisting',
            old_name='exterior_color',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='vehiclelisting',
            old_name='interior_color',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='vehiclelisting',
            old_name='mileage',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='fuel_economy',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='listing_url',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='stock_number',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='vin',
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='msrp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
