# Generated by Django 3.2.25 on 2024-07-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20240706_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('listings_added', models.IntegerField(default=0)),
                ('listings_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='needs_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
