# Generated by Django 3.2.25 on 2024-07-11 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraper', '0006_syncattempt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelisting',
            name='make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
