# Generated by Django 3.2.25 on 2024-07-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20240711_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelisting',
            name='make',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='model',
            field=models.TextField(),
        ),
    ]
